###
GET http://localhost:3000/builders


###
GET http://localhost:3000/builders/65c52b291aba6758e4b0aa5a

###
POST http://localhost:3000/builders
content-type: application/json

{
        "firstName": "Mario",
        "lastName": "Correa",
        "email": "marioC@gmail.com",
        "favoriteTheme": "Technic",
        "setsOwned": [42162, 42141, 75572, 60367],
        "wishList": [10300, 42096]
      }
