// Local host GET, GET/:id, POST for Builders

###
GET http://localhost:3000/builders

###
GET http://localhost:3000/builders/:id

###
POST http://localhost:3000/builders
content-type: application/json

{
  "firstName": "Mario",
  "lastName": "Correa",
  "email": "marioC@gmail.com",
  "favoriteTheme": "Technic",
  "setsOwned": [42162, 42141, 75572, 60367],
  "wishList": [10300, 42096]
}

// Render GET, GET/:id, POST for Builders

###
GET https://lastclassprojecttwo.onrender.com/builders

###
GET https://lastclassprojecttwo.onrender.com/builders/:id

###
POST https://lastclassprojecttwo.onrender.com/builders
content-type: application/json

{
  "firstName": "Mario",
  "lastName": "Correa",
  "email": "marioC@gmail.com",
  "favoriteTheme": "Technic",
  "setsOwned": [42162, 42141, 75572, 60367],
  "wishList": [10300, 42096]
}

// Local host GET, GET/:id, POST for Sets

###
GET http://localhost:3000/sets

###
GET http://localhost:3000/sets/:id

###
POST http://localhost:3000/sets
content-type: application/json

  {
      "setNumber": 10305,
      "setName": "Lion Knights' Castle",
      "theme": "LEGO Icons",
      "pieces": 4514,
      "ages": "18+",
      "price": 399.99,
      "availability": "Will ship in 60 days",
      "image": "https://www.lego.com/cdn/cs/set/assets/blt0254ea3dce736ea0/10305.png?format=webply&fit=bounds&quality=75&width=800&height=800&dpr=1"
  }

// Render GET, GET/:id, POST for Sets

###
GET https://lastclassprojecttwo.onrender.com/sets

###
GET https://lastclassprojecttwo.onrender.com/sets/:id

###
POST https://lastclassprojecttwo.onrender.com/sets
content-type: application/json

  {
      "setNumber": 10305,
      "setName": "Lion Knights' Castle",
      "theme": "LEGO Icons",
      "pieces": 4514,
      "ages": "18+",
      "price": 399.99,
      "availability": "Will ship in 60 days",
      "image": "https://www.lego.com/cdn/cs/set/assets/blt0254ea3dce736ea0/10305.png?format=webply&fit=bounds&quality=75&width=800&height=800&dpr=1"
  }
